site_name: AWS SCP Examples
nav:
  - About: index.md
  - SCP Security Examples: security.md
theme: 
  name: material
  palette:
    scheme: default
    primary: amber
    accent: orange
  language: en
  features:
    - navigation.tracking
    - toc.integrate
    - content.code.copy
    - content.action.view
    - content.action.edit
  icon:
    logo: material/cloud
    repo: fontawesome/brands/github 
    edit: material/pencil 
    view: material/eye
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - offline
repo_url: https://github.com/almeida-matheus/aws-scp-examples
repo_name: aws-scp-examples
edit_uri: edit/main/docs/