site_name: AWS Organizations Policies
nav:
  - About: index.md
  - SCP Examples: aws-scp-examples.md
  - RCP Examples: aws-rcp-examples.md
theme:
  name: material
  palette:
    scheme: default
    primary: amber
    accent: orange
  language: en
  features:
    - navigation.tracking
    - toc.integrate
    - content.code.copy
    - content.action.view
    - content.action.edit
  icon:
    logo: material/cloud
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - offline
repo_url: https://github.com/almeida-matheus/aws-organizations-policies
repo_name: aws-organizations-policies
edit_uri: edit/main/docs/