name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "mkdocs.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
      - "mkdocs.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install python dependencies
        run: python -m pip install --upgrade pip && pip install mkdocs mkdocs-material
      - name: build and deploy
        run: |
          mkdocs build --clean
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          mkdocs gh-deploy --force
